package controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.TableView;

public class ReportsViewController {
	@FXML
	private TableView tableView;
	@FXML
	private Button top10BooksBtn;
	@FXML
	private Button top5UserBtn;
	@FXML
	private Button totalSalesBtn;
	@FXML
	private Label totalSales;
	@FXML
	private Label errorLabel;

	// Event Listener on Button[#top10BooksBtn].onAction
	@FXML
	public void showTop10BooksListener(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#top5UserBtn].onAction
	@FXML
	public void showTop5UserListener(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#totalSalesBtn].onAction
	@FXML
	public void showTotalSalesListener(ActionEvent event) {
		// TODO Autogenerated
	}
}
